const styles = {
  root: {
    backgroundColor: "#f8f9fa",
    // backgroundColor: "#fff",
    zIndex: "20",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1em",
    color: "black",
    position: "fixed",
    width: "100%",
    top: 0,
  },
  logo: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    // justifyContent: "space-between",
    fontSize: "1.8em",
    "& img": {
      marginLeft: "5px",
      // fontFamily: "Monoton, cursive",
      textTransform: "uppercase",
      color: "#212529",
      width: "150px",
      // fontSize: "2em",
      // fontWeight: "normal",
    },
  },
  links: {
    // display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "40%",
    maxWidth: "250px",
    "& a:hover": {
      // color: "orange",
      backgroundColor: "lightgray",
    },
    "& button:hover": {
      // color: "orange",
      backgroundColor: "lightgray",
    },
    position: "absolute",
    // inset: "0px 0px 0px 0px",
    backgroundColor: "white",
    // right: "0px",
    height: "100vh",
    top: 0,
    bottom: 0,
    right: 0,
    zIndex: "13",
    "& a": {
      color: "black",
      display: "block",
      padding: "1em 2em",
    },
    "& button": {
      color: "black",
      display: "block",
      width: "100%",
      padding: "1em 2em",
      textAlign: "left",
    },
  },
  overlay: {
    position: "fixed",
    backgroundColor: "rgba(0,0,0,0.3)",
    width: "100%",
    height: "100vh",
    inset: 0,
    zIndex: "10",
  },
  cart: {
    position: "relative",
    "& span": {
      position: "absolute",
      right: "0",
      bottom: "25px",
      backgroundColor: "black",
      color: "white",
      padding: "5px",
      borderRadius: "50%",
      width: "18px",
      height: "18px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
    },
  },
};

export default styles;
